[workspace]
members = [
	"bencher",
	"bencher/bencher-procedural",
	"bencher/test",
	"weight-gen",
	"weight-meter",
	"weight-meter/weight-meter-procedural",
]

exclude = ["bencher/test"]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[workspace.dependencies]
frame-support = { version = "25.0.0", default-features = false }
frame-system = { version = "25.0.0", default-features = false }
pallet-balances = { version = "25.0.0", default-features = false }
sc-client-db = { version = "0.32.0", default-features = false }
sc-executor = { version = "0.29.0", default-features = false }
sc-executor-common = { version = "0.26.0", default-features = false }
sp-core = { version = "25.0.0", default-features = false }
sp-externalities = { version = "0.23.0", default-features = false }
sp-io = { version = "27.0.0", default-features = false }
sp-maybe-compressed-blob = { version = "9.0.0", default-features = false }
sp-runtime = { version = "28.0.0", default-features = false }
sp-runtime-interface = { version = "21.0.0", default-features = false }
sp-state-machine = { version = "0.32.0", default-features = false }
sp-std = { version = "12.0.0", default-features = false }
sp-storage = { version = "17.0.0", default-features = false }
